### ISSUE TITLE
Explained how to install, but not how to use.

### ISSUE THREAD

**Issue by wyntrson** [Petronian/dynamic-cards#1]
It'd be great if you add another line to the readme.md so we can know how to use the addon after installation.

**Comment by studentjunk** [comment]
My understanding is that it is supposed to work automatically when enabled.

**Comment by Petronian** [comment]
Good note. It is supposed to work automatically when enabled, but it's very subtle. Will work on this for next update; would an initial pop-up (kind of like other extensions) be something you're looking for? @wyntrson

**Comment by wyntrson** [comment]
> Good note. It is supposed to work automatically when enabled, but it's very subtle. Will work on this for next update; would an initial pop-up (kind of like other extensions) be something you're looking for? @wyntrson

I think it'd benefit anyone who'll use this extension. 
Thank you for your work and making our lives easier.

**Comment by Petronian** [comment]
[Branch 0.3.0](/petronian/dynamic-cards/tree/0.3.0) (edit: now defunct) should have these changes fixed and some other enhancements; if you want to download the extension from GitHub and bug-test it in Anki, that'd be great! Otherwise, will do so myself and release in a couple of days once everything is cleaned up.

**Comment by Petronian** [comment]
Updated and merged into master branch. Reopen the thread if issues persist/the README was not appropriately fixed. Thanks for the feedback!
